# dataset info
seen_class : 26
unseen_class : 11
total_class : 37
num_points: 2048
use_normals: false
train_dataset_dir : 'data/ModelNet/'
eval_dataset_dir : 'data/ScanObjectNN/'
zs_classes_text_path: "./data/ScanObjectNN/unseen_text_classes_scanobjectnn.txt"
gzs_classes_text_path: "./data/ScanObjectNN/seen_unseen_text_classes_modelnet40_scanobjectnn.txt"
zs_classes_path: "./data/ScanObjectNN/unseen_classes_scanobjectnn.txt"
gzs_classes_path: "./data/ScanObjectNN/seen_unseen_classes_modelnet40_scanobjectnn.txt"
bachbone_features_size: 1024
embbeding_size: 128

bert_text_embeddings_path: "./data/bert_text_embedding.mat"
bert_text_embedding_size: 768
glove_text_embeddings_path: "./data/glove_text_embedding.mat"
glove_text_embedding_size: 300
w2v_text_embeddings_path: "./data/w2v_text_embedding.mat"
w2v_text_embedding_size: 300


# training paths and parameters
checkpoints_dir : 'checkpoints/pointnet_modelnet40_scanobjectnn'
logs_dir: 'runs/pointnet_modelnet40_scanobjectnn'
epoch : 100
batch_size : 48
lr : 1e-3
wd : 1e-6



# network parameters
k: 40
feature_transform: true
alpha_sceneaug: 0.1
