# dataset info
seen_class : 30
unseen_class : 10
total_class : 40
num_points: 2048
use_normals: false
dataset_dir : 'data/ModelNet/'
zs_classes_text_path: "./data/ModelNet/zs_text_classes_modelnet40.txt"
gzs_classes_text_path: "./data/ModelNet/gzs_text_classes_modelnet40.txt"
bachbone_features_size: 2048
embbeding_size: 128

text_embeddings_path: "./data/ModelNet/bert_txt_embedding_modelnet40.mat"
text_embedding_size: 768
# text_embeddings_path: "./data/ModelNet/word2vec_modelnet40.mat"
# text_embedding_size: 300


# training paths and parameters
checkpoints_dir : 'checkpoints/edgeconv_modelnet'
logs_dir: 'runs/edgeconv_modelnet'
epoch : 250
batch_size : 8
lr : 1e-3
wd : 1e-4



# network parameters
k: 20 # knn
alpha_sceneaug: 0.1